### ISSUE TITLE
Option for Single or Double Quotes?

### ISSUE THREAD

**Issue by sabriele** [Heedster/ExpressComplete#4]
Hi there, I do know that single/double quotes is a rather small matter of personal preference. I have tweaked your code slightly to replace all single ( ' ) quotes with back-slashed double quotes ( \" ); would you be interested if I submitted a pull request?

**Comment by Heedster** [comment]
Could you tell me why the change? 

As per ExpressJS API Docs, single quotes are preferred over double quotes.

**Comment by sabriele** [comment]
You're right, the Docs do show a preference for single quotes. I prefer the double quotes simply because they 'gel' better with my existing JS files, where I use double quotes more often (strings with apostrophes in them are more common for me) but I think your rationale does make a lot of sense. Thanks.
