### ISSUE TITLE
I write similar completion

### ISSUE THREAD

**Issue by fakhrullah** [Heedster/ExpressComplete#5]
Hi Jamsheed,

I create similar Express JS completion and has almost complete list of completion. You can see [here](https://github.com/fakhrullah/sublime-expressjs-4-completion).

There are some differences in how our completion trigger. So, I do not know if you like this or not. Please see it first and if you like it, I will forked yours and add my completion directory to this.

I message you because I do not want to learn how to add mine to sublime package control list. After all our package doing same thing.

**Comment by Heedster** [comment]
Please refer to https://packagecontrol.io/docs/submitting_a_package

**Comment by Heedster** [comment]
Sorry, misread your post. 

Looks good. Once done, open a pull request, i will merge. As of now i dont work with expressjs much, so does not get time to update this repo. would be of good help to the users.

**Comment by fakhrullah** [comment]
:smile: Done.
